### ISSUE TITLE
docker  :  fdroid build -v -l org.mozilla.fennec_fdroid

### ISSUE THREAD

**Issue by QGB** [QGB/firefox-android#2]
python3 -m pip install -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com fdroidserver
sdkmanager "ndk;21.3.6528147" # r21d

above installed in  /root/docker/mingc/android-build-box/

docker run -it -v /root/:/root/ -v /home/qgb/:/home/qgb/ -v /root/docker/mingc/android-build-box/usr/local:/usr/local -v /root/docker/mingc/android-build-box/opt:/opt -p 4000:4000 mingc/android-build-box:1.26.0 bash

```
cd /home/qgb/gitlab/fdroiddata
apt update;apt install -y git mercurial ninja-build tcl tk;fdroid build -v -l org.mozilla.fennec_fdroid 



ln -s /bin/python3 /usr/local/bin/python

python3 -m pip install git+https://github.com/chromium/gyp

```

###cd /home/qgb/gitlab/fdroiddata/build/org.mozilla.fennec_fdroid
add head `\\192.168.1.10\qgb\gitlab\fdroiddata\build\srclib\MozBuild\build.sh`  and run
```
set -x		# ECHO on
export PATH=$PATH:/root/.gradle/wrapper/dists/gradle-7.5.1-bin/7jzzequgds1hbszbhq3npc5ng/gradle-7.5.1/bin
echo $PWD $(date) $(env) /home/qgb/gitlab/fdroiddata/build/srclib/MozBuild/build.sh $@  >> /root/hg.log

```

**Comment by QGB** [comment]
/home/qgb/gitlab/err/org.mozilla.fennec_fdroid.yml

文件末尾 需要修改 scanignore

```
  - versionName: 117.0.0
    versionCode: 1170020
    commit: fenix-v117.0
    timeout: 18000
    sudo:
      - apt-get update
      - apt-get install -y cmake make m4 g++ pkg-config libssl-dev python-is-python3
        python3-distutils python3-venv tcl gyp ninja-build bzip2 libz-dev libffi-dev
        libsqlite3-dev
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    output: fenix/app/build/outputs/apk/fenix/release/app-*-release-unsigned.apk
    srclibs:
      - FirefoxAndroidAS@components-v115.0.1
      - MozAppServices@v117.0
      - MozBuild@1027621811a616d004c94b889cf2f6f6984fc331
      - MozFennec@FIREFOX_117_0_RELEASE
      - MozGlean@v53.1.0
      - MozGleanAS@v52.7.0
      - rustup@1.26.0
      - wasi-sdk@wasi-sdk-16
    prebuild: $$MozBuild$$/prebuild.sh $$VERSION$$ $$VERCODE$$
    scanignore:
      - android-components/components/lib/publicsuffixlist/src/main/assets/publicsuffixes
    build: $$MozBuild$$/build.sh
    ndk: r21d

  - versionName: 117.0.1
    versionCode: 1170100
    commit: fenix-v117.0.1
    timeout: 18000
    sudo:
      - apt-get update
      - apt-get install -y cmake make m4 g++ pkg-config libssl-dev python-is-python3
        python3-distutils python3-venv tcl gyp ninja-build bzip2 libz-dev libffi-dev
        libsqlite3-dev
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    output: fenix/app/build/outputs/apk/fenix/release/app-*-release-unsigned.apk
    srclibs:
      - FirefoxAndroidAS@components-v115.0.1
      - MozAppServices@v117.0
      - MozBuild@1027621811a616d004c94b889cf2f6f6984fc331
      - MozFennec@FIREFOX_117_0_RELEASE
      - MozGlean@v53.1.0
      - MozGleanAS@v52.7.0
      - rustup@1.26.0
      - wasi-sdk@wasi-sdk-16
    prebuild: $$MozBuild$$/prebuild.sh $$VERSION$$ $$VERCODE$$
    scanignore:
      - android-components/components/lib/publicsuffixlist/src/main/assets/publicsuffixes
    build: $$MozBuild$$/build.sh
    ndk: r21d

  - versionName: 117.0.1
    versionCode: 1170120
    commit: fenix-v117.0.1
    timeout: 18000
    sudo:
      - apt-get update
      - apt-get install -y cmake make m4 g++ pkg-config libssl-dev python-is-python3
        python3-distutils python3-venv tcl gyp ninja-build bzip2 libz-dev libffi-dev
        libsqlite3-dev
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    output: fenix/app/build/outputs/apk/fenix/release/app-*-release-unsigned.apk
    srclibs:
      - FirefoxAndroidAS@components-v115.0.1
      - MozAppServices@v117.0
      - MozBuild@1027621811a616d004c94b889cf2f6f6984fc331
      - MozFennec@FIREFOX_117_0_RELEASE
      - MozGlean@v53.1.0
      - MozGleanAS@v52.7.0
      - rustup@1.26.0
      - wasi-sdk@wasi-sdk-16
    prebuild: $$MozBuild$$/prebuild.sh $$VERSION$$ $$VERCODE$$
    scanignore: 
      - android-components/components/lib/push-firebase
    build: $$MozBuild$$/build.sh
    ndk: r21d

MaintainerNotes: |-
  Version code scheme:
  XYZAR, where X.Y.Z is upstream version, A is architecture (0 = ARMv7, 1 = x86, 2 = ARMv8), R is revision (if we need to re-release).
  * Example: 530210 = Firefox 53.0.2 for x86, initial revision
  * Example: 550021 = Firefox 55.0 for ARMv8, second revision

  MozAppServices, Glean and MozFennec versions:
  grep 'mozilla_appservices =' build/org.mozilla.fennec_fdroid/android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  grep 'mozilla_glean =' build/org.mozilla.fennec_fdroid/android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  grep 'version =' build/org.mozilla.fennec_fdroid/android-components/plugins/dependencies/src/main/java/Gecko.kt

  MozAndroidComponentsAS version:
  grep 'android_components_version =' build/srclib/MozAppServices/build.gradle

  MozGleanAS version:
  grep 'mozilla_glean =' build/srclib/FirefoxAndroidAS/android-components/buildSrc/src/main/java/Dependencies.kt

  wasi-sdk version:
  grep -A5 '^wasi-sdk:' build/srclib/MozFennec/taskcluster/ci/fetch/toolchains.yml

  Rust:
  * https://github.com/rust-lang/rustup/tags
  * https://www.rust-lang.org/


AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 117.0.1
CurrentVersionCode: 1170120

```
